"""Matriz de transformação: análises do catálogo anterior (D, J, M, X, P, T) -> capítulos do livro."""
M = [
    # código, capítulo, bases, gráficos, tabelas, fonte primária, decisões, derivado, limitação, risco
    ("D1", "6", "doacoes_campanha", "c01, c02, i2", "t_d1_mix", "TSE", "D-043, D-070", "Parcela por tipo de doador; totais nominais e reais", "Só eleitos; 2002 com tipo deduzido", "Ler a mudança como efeito sobre quem se elege"),
    ("D2", "7", "doacoes_campanha", "c03", "—", "TSE; IBGE", "D-043, D-070", "Mediana e percentis, nominais e reais", "Só eleitos", "Comparar valores nominais de anos distantes"),
    ("D3", "8", "doacoes_campanha", "c04", "t_d3_conc", "TSE", "D-043", "Parcela dos 10% maiores; Gini; Lorenz", "Desigualdade entre eleitos, não entre candidatos", "Concentração como desigualdade de chance eleitoral"),
    ("D4", "7; Atlas", "doacoes_campanha", "—", "—", "TSE", "D-043", "Soma das duas maiores campanhas majoritárias", "Presidenciáveis sem eleição entram", "Protagonismo individual"),
    ("D5", "9 (nota); Atlas A", "doacoes_campanha, instituicoes", "—", "atlas_empresas", "TSE", "D-030, D-043, D-071", "Totais por empresa nomeada", "128 empresas, cerca de 8% do valor; seleção", "Tomar as nomeadas como as maiores doadoras"),
    ("D6", "Retirada (D-071); agenda T3", "doacoes_campanha, eventos", "—", "—", "TSE; CGU", "D-027, D-030, D-071", "—", "Viés de seleção", "Ler leniência como prova sobre a doação"),
    ("D7", "Retirada como cruzamento (D-071); BNDES no cap. 30", "doacoes_campanha, operacoes_exportacao_bndes", "—", "—", "TSE; BNDES", "D-021, D-030, D-071", "—", "Seleção; valor do BNDES só até 2015", "Doação como contrapartida de crédito"),
    ("D8", "9", "doacoes_campanha, filiacoes, cargos", "c09", "t_d8_partido", "TSE; Câmara; Senado", "D-016, D-043", "Fundo por partido, total e por eleito", "Só deputados e senadores", "Fundo maior como favorecimento"),
    ("D9", "9", "doacoes_campanha, filiacoes", "c10", "t_d9_partido", "TSE; Câmara; Senado", "D-016, D-043", "Doações de empresas por partido, total e por eleito", "DEM inclui PFL", "Afinidade entre empresas e partidos"),
    ("D10", "7", "doacoes_campanha", "c11", "—", "TSE; IBGE", "D-043, D-070", "Recursos próprios, nominais e reais", "Regra de teto não registrada na base", "Queda como mudança de comportamento"),
    ("D11", "5 (nota estatística)", "doacoes_campanha, status_pessoa_processo", "—", "t_testes", "TSE; STF", "D-065", "Médias por grupo", "Grupo inclui absolvidos; sem direção estável", "Associação entre dinheiro e processo"),
    ("J1", "18; 19", "processos, fases_processo", "i1, c13, c14", "t_j1_desfechos, t_j1_longas", "STF", "D-037, D-068", "Parcela por desfecho; tempo", "Destino após o declínio não observado", "Declínio como impunidade"),
    ("J2", "20", "status_pessoa_processo", "c15", "t_j5_status_ano", "STF", "D-065, D-066", "Status por ano", "30 casos", "Prescrição como absolvição ou culpa"),
    ("J3", "20; Atlas A", "status_pessoa_processo", "—", "atlas_condenacoes", "STF", "D-046, D-065, D-071", "Lista de condenações com contexto", "Recursos e trânsito não lidos", "Condenação vigente presumida"),
    ("J4", "18", "fases_processo", "c16", "t_j1_desfechos", "STF", "D-068", "Desfechos por ano", "Motivo do declínio não registrado", "Ondas como manobra"),
    ("J5", "20", "status_pessoa_processo", "c13, c15", "t_j5_status_ano", "STF", "D-065", "Distribuição de status", "Procedência parcial contada como condenação", "Taxa de condenação como medida de rigor"),
    ("J6", "18", "fases_processo, filiacoes, governo_oposicao_partidos", "c17", "t_j6_declinio_grupo", "STF; Câmara (orientações)", "D-050, D-051, D-067", "Taxa por grupo; Fisher", "Sem correção múltipla; motivo não medido", "Favorecimento ou perseguição"),
    ("J7", "17", "stf_composicao, relacoes", "c18", "t_j7_stf", "STF", "D-058, D-059", "Tempo de mandato", "Erros das páginas corrigidos (D-058)", "Indicação como orientação do ministro"),
    ("J8", "5 (nota estatística)", "status_pessoa_processo, relacoes", "c19 (sem nomes)", "t_testes", "STF", "D-067", "Taxa e intervalo por relator", "2 a 12 casos por ministro", "Ranking de ministros"),
    ("J9", "21; Atlas A", "status_pessoa_processo, eixo1_taxas", "c20", "t_j9_candidaturas, atlas_tcu", "TCU; TSE", "D-060, D-061, D-064", "Decisões por ano; taxas por candidatura", "Lista sem revisões; função de gestor", "Conta irregular como crime"),
    ("J10", "21", "eventos", "c21", "—", "CGU", "D-027", "Sanções e acordos por ano", "Adesão ao cadastro muda a série", "Aumento de infrações"),
    ("M1", "11", "emendas_parlamentares", "c22, n07", "t_m1_tipo", "CGU; Tesouro; IBGE", "D-029, D-070", "Pago por tipo, real e em % da despesa", "2014–2016 fora; critérios de registro diferentes", "Crescimento como aumento de desvio"),
    ("M2", "12", "emendas_parlamentares", "c23, i3", "t_m1_tipo", "CGU", "D-029", "Pago por modalidade", "—", "Transferência especial como irregular"),
    ("M3", "12", "emendas_parlamentares", "c24", "—", "CGU", "D-029", "Empenhado e pago", "Decisão do STF com referência a confirmar", "Ausência de autor como ocultação deliberada"),
    ("M4", "14", "emendas_parlamentares", "c25, n09", "t_m4_funcao, t_m4_uf", "CGU; IBGE", "D-029, D-070", "Pago por função e por habitante", "Função declarada; parte do valor sem UF", "Destino declarado como uso efetivo"),
    ("M5", "15; Atlas A", "emendas_parlamentares, atores", "n10", "atlas_autores_emendas", "CGU", "D-029", "Concentração por autor", "Tempo de mandato pesa", "Volume como influência"),
    ("M6", "13", "emendas_parlamentares", "c27, i3", "t_m6_autor", "CGU", "D-029", "Valor com e sem autor", "Falta é da fonte", "Sem autor = secreto"),
    ("M7", "15", "emendas_parlamentares, filiacoes, cargos", "c28", "—", "CGU; Câmara; Senado", "D-016, D-029", "Pago por partido e por parlamentar-ano", "Só emendas com autor individual", "Partido do governo favorecido"),
    ("M8", "16", "emendas_parlamentares", "c29", "—", "CGU", "D-029", "Pago/empenhado", "Restos a pagar", "Execução como bloqueio político"),
    ("X1", "29", "votos_multilaterais", "c30, c30b", "t_x1_pais", "ONU; OEA", "D-031, D-032, D-036, D-044", "Contagem por voto e país", "Seleção temática", "Voto como alinhamento ideológico"),
    ("X2", "29", "votos_multilaterais, qualidade_democratica", "c31", "t_x2_periodo", "ONU; OEA; V-Dem; Freedom House", "D-053", "Parcela de sim por período e régua", "Réguas divergem", "Período como causa"),
    ("X3", "30", "operacoes_exportacao_bndes", "c08, c32, n18", "t_x3_periodo", "BNDES", "D-021, D-053", "Valores e operações por destino", "Valor só de serviços até 2015", "Crédito como apoio político"),
    ("X4", "31", "eixo2_comercio_por_governo", "c33", "—", "ComexStat (fonte a registrar); Freedom House", "D-054", "Parcelas com e sem China", "47% de 2023+ sem classificação FH", "Comércio como escolha de governo"),
    ("X5", "32", "acordos_bilaterais", "c34, c34b", "t_x5_periodo", "Itamaraty", "D-041", "Atos por ano e país", "Contagem não mede intensidade", "Mais atos = mais proximidade"),
    ("X6", "28", "qualidade_democratica", "c35, n17", "—", "V-Dem; Freedom House", "D-003, D-017, D-018", "Séries do Brasil; concordância", "Incerteza de modelo; FH sem 2025", "Queda como efeito de um governo"),
    ("X7", "28", "qualidade_democratica", "c36", "—", "Freedom House", "D-018, D-019", "Países por status", "Cobertura anual varia", "Tendência mundial como causa"),
    ("P1", "23", "filiacoes, denominacoes_partido, instituicoes", "c37, c37b", "t_p1_trajetos, t_p_fusoes", "Câmara; Senado; TSE", "D-016, D-072", "Mudanças individuais e por fusão", "Filiação só durante o mandato", "Troca como fisiologismo"),
    ("P2", "24", "governo_oposicao_partidos, cargos", "c38, n15", "t_p2_matriz", "Câmara (orientações)", "D-050, D-051", "Concordância; cadeiras por grupo", "Blocos após 2023; só Câmara", "Alinhamento como cargo na coalizão"),
    ("P3", "26; Atlas A", "etica_desfechos", "c39", "atlas_cassacoes", "Câmara; Senado", "D-063", "Funil de desfechos", "157 sem desfecho estruturado", "Arquivamento como absolvição moral"),
    ("P4", "26", "etica_desfechos", "c40", "—", "Câmara; Senado", "D-063", "Dias até o desfecho", "Datas da fonte", "Rapidez como rigor"),
    ("P5", "26", "etica_desfechos", "c41", "—", "Câmara; Senado", "D-063", "Vínculos por ano", "Uma representação, vários alvos", "Ondas como crise moral"),
    ("P6", "26 (contagem)", "etica_desfechos", "—", "—", "Câmara; Senado", "D-063", "Parlamentares com 3 ou mais representações", "Representação não é mérito", "Reincidência como culpa"),
    ("P7", "26", "etica_taxas", "c42", "t_p7_faixa", "Câmara; Senado; Bolognesi, Ribeiro e Codato (2023)", "D-062, D-063", "Taxa por faixa, com e sem a 52ª legislatura", "Concentração em poucos episódios", "Ideologia como causa"),
    ("P (novo)", "22", "cargos, filiacoes, consulta_cand (TSE)", "n13", "t_p_nep", "TSE; Câmara", "D-073", "Número efetivo de partidos", "Filiação só durante o mandato", "Reconcentração atribuída a uma só regra"),
    ("T1", "Atlas C", "bruto TSE, despesas 2018 e 2022", "—", "—", "TSE", "—", "—", "Não processado", "—"),
    ("T2", "Atlas C", "bruto TSE, notas fiscais e extratos partidários (fora do manifesto)", "—", "—", "TSE", "—", "—", "Não processado; arquivos sem registro", "Fornecedor comum como conluio"),
    ("T3", "Atlas C", "bruto TSE, receitas 2002 a 2014", "—", "—", "TSE", "—", "—", "Não processado", "Mesmo de D6 e D7"),
    ("T4", "Atlas C", "bruto TSE, bens 2006 a 2022 (fora do manifesto)", "—", "—", "TSE", "—", "—", "Não processado; dado pessoal", "Enriquecimento como ilícito"),
    ("T5", "Atlas C", "fefc_fp_2022", "—", "—", "TSE", "—", "—", "Não processado", "Diferença como discriminação deliberada"),
    ("T6", "Atlas C; parte no cap. 21", "motivo_cassacao 2014 a 2022", "—", "t_j9_candidaturas", "TSE", "D-060, D-061", "Motivos por eleição", "2014 com 10 linhas", "Cassação como prova de crime"),
    ("T7", "Atlas C", "consulta_coligacao 2002 a 2022", "—", "—", "TSE", "—", "—", "Não processado", "Coligação como afinidade programática"),
    ("Parte VII", "34 a 38", "todas", "n20, n21, n22", "t_painel, t_marcos", "as de cada série", "D-070, D-071", "Escore z; ano de maior mudança", "Séries curtas e com inícios diferentes", "Simultaneidade como causa"),
]
COLS = ["Análise", "Capítulo", "Bases", "Gráficos", "Tabelas", "Fonte primária", "Decisões", "Dado derivado", "Principal limitação", "Risco de interpretação indevida"]
